# Generated by Django 4.1 on 2022-09-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[], default=('pending', 'Pending'), max_length=100),
        ),
    ]
